"""v0

Revision ID: 8258641dc68e
Revises: 
Create Date: 2020-03-11 14:27:05.662698

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8258641dc68e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tb_pessoa',
        sa.Column('guid', sa.String(), nullable=False),
        sa.Column('nome', sa.String(), nullable=True),
        sa.Column('documento', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('guid')
    )

    op.create_table(
        'tb_processo',
        sa.Column('guid', sa.String(), nullable=False),
        sa.Column('numero', sa.String(), nullable=True),
        sa.Column('data', sa.DateTime(), nullable=True),
        sa.Column('valor', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('guid')
    )

    op.create_table(
        'tb_parte',
        sa.Column('guid', sa.String(), nullable=False),
        sa.Column('pessoa_guid', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['pessoa_guid'], ['tb_pessoa.guid'], ),
        sa.PrimaryKeyConstraint('guid')
    )

    op.create_table(
        'tb_relacao_processo_parte',
        sa.Column('processo_guid', sa.String(), nullable=True),
        sa.Column('parte_guid', sa.String(), nullable=True),
        sa.Column('tipo_parte', sa.Enum('EXEQUENTE', 'EXECUTADO', 'TESTEMUNHA', 'TERCEIRO', name='tipoparte'), nullable=True),
        sa.ForeignKeyConstraint(['parte_guid'], ['tb_parte.guid'], ),
        sa.ForeignKeyConstraint(['processo_guid'], ['tb_processo.guid'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_processo_parte')
    op.drop_index(op.f('ix_tb_parte_pessoa_guid'), table_name='tb_parte')
    op.drop_table('tb_parte')
    op.drop_table('tb_processo')
    op.drop_table('tb_pessoa')
    # ### end Alembic commands ###
